apiVersion: v1
kind: Service
metadata:
  name: trend-service
  labels:
    app: trend
spec:
  type: LoadBalancer
  selector:
    app: trend
  ports:
    - port: 80        # external port (ELB)
      targetPort: 80  # must match containerPort in Deployment
      protocol: TCP

